
		<div class="container">
		  <hr>
		  <footer>
			<p>&copy; Compa&ntilde;ia 2013</p>
		  </footer>
		</div> <!-- /container -->

		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="<?php echo $this->path?>/js/vendor/jquery-1.10.1.min.js"><\/script>')</script>

        <script src="<?php echo $this->path?>/js/vendor/bootstrap.min.js"></script>

        <script src="<?php echo $this->path?>/js/plugins.js"></script>
        <script src="<?php echo $this->path?>/js/main.js"></script>

        <script>
            var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
            g.src='//www.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>
    </body>
</html>
