<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title><?php echo $this->textoTituloPagina?></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

        <link rel="stylesheet" href="<?php echo $this->path?>/css/bootstrap.min.css">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
        <link rel="stylesheet" href="<?php echo $this->path?>/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="<?php echo $this->path?>/css/main.css">
		
		<!-- Favicons  -->
		<link rel="shortcut icon"    href="<?php echo $this->path?>/img/favicon.ico">
		<link rel="apple-touch-icon" href="<?php echo $this->path?>/img/apple-touch-icon.png">
		<link rel="apple-touch-icon" sizes="57x57"   href="<?php echo $this->path?>/img/apple-touch-icon-57x57-precomposed.png">
		<link rel="apple-touch-icon" sizes="72x72"   href="<?php echo $this->path?>/img/apple-touch-icon-72x72-precomposed.png">
		<link rel="apple-touch-icon" sizes="114x114" href="<?php echo $this->path?>/img/apple-touch-icon-114x114-precomposed.png">
		<link rel="apple-touch-icon" sizes="144x144" href="<?php echo $this->path?>/img/apple-touch-icon-144x144-precomposed.png">

        <script src="<?php echo $this->path?>/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">
				Est&aacute;s usando un browser <strong>desactualizado</strong>. Por favor <a href="http://browsehappy.com/">actualiza tu browser</a> o <a href="http://www.google.com/chromeframe/?redirect=true">activa Google Chrome Frame</a> para mejorar tu experiencia.
			</p>
        <![endif]-->