		<div class="navbar navbar-inverse navbar-fixed-top">
		  <div class="container">
			<div class="navbar-header">
			  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			  </button>
			  <a class="navbar-brand" href="#">Nombre del proyecto</a>
			</div>
			<div class="navbar-collapse collapse">
			  <ul class="nav navbar-nav">
				<li class="active"><a href="#">Home</a></li>
				<li><a href="#about">Sobre nosotros</a></li>
				<li><a href="#contact">Contacto</a></li>
				<li class="dropdown">
				  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
				  <ul class="dropdown-menu">
					<li><a href="#">Acci&oacute;n</a></li>
					<li><a href="#">Otra acci&oacute;n</a></li>
					<li><a href="#">Algo m&aacute;s aqu&iacute;</a></li>
					<li class="divider"></li>
					<li class="dropdown-header">Posible t&iacute;tulo</li>
					<li><a href="#">Link Separado</a></li>
					<li><a href="#">Otro link separado</a></li>
				  </ul>
				</li>
			  </ul>
			  <form class="navbar-form navbar-right">
				<div class="form-group">
				  <input type="text" placeholder="Email" class="form-control">
				</div>
				<div class="form-group">
				  <input type="password" placeholder="Password" class="form-control">
				</div>
				<button type="submit" class="btn btn-success">Logeate</button>
			  </form>
			</div><!--/.navbar-collapse -->
		  </div>
		</div>
