<?php
	require_once 'views/commons/header.phtml';
	require_once 'views/commons/navbar.phtml';
?>

		<!-- jumbotron principal como principal mensaje de marketing o llamado por una acción -->
		<div class="jumbotron">
		  <div class="container">
			<h1>Hola, Mundo!!</h1>
			<p>Este es una planilla para un sitio web informativo o de marketing simple. Incluye una gran leyenda llamada jumbotron y tres piezas de soporte para contenido. Usalos como punto de partida para crear algo m&aacute;s &uacute;nico.</p>
			<p><a class="btn btn-primary btn-lg">M&aacute;s Informaci&oacute;n &raquo;</a></p>
		  </div>
		</div>

		<div class="container">
		  <!-- Ejemplo de fila y columnas -->
		  <div class="row">
			<div class="col-lg-4">
			  <h2>Titulo 1</h2>
			  <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
			  <p><a class="btn btn-default" href="#">Ver m&aacute;s detalles &raquo;</a></p>
			</div>
			<div class="col-lg-4">
			  <h2>Titulo 2</h2>
			  <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
			  <p><a class="btn btn-default" href="#">Ver m&aacute;s detalles &raquo;</a></p>
		   </div>
			<div class="col-lg-4">
			  <h2>Titulo 3</h2>
			  <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
			  <p><a class="btn btn-default" href="#">Ver m&aacute;s detalles &raquo;</a></p>
			</div>
		  </div>
		</div> <!-- /container -->
		
<?php
	require_once 'views/commons/footer.phtml';